spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/mmdf?serverTimezone=Asia/Taipei"
    username: "root"
    password: "Tgk89bid"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update
  # redis快取設定
  data:
    redis:
      host: "localhost"
      port: 6379
      password: "mmdf"

logging:
  file:
    path: "logs/"

config:
  # 是否使用local環境運行
  use-local: false
  #  跨域允許網域
  cors-allow-origin: "*"
  # 是否使用local方式啟動，自己測試環境時可換成true
  use-test-member: false
  # 測試使用者用登入憑證
  test-member-authorization: "A123456789"
  # 測試使用者帳號
  member-account: "testAccount"
  # 測試使用者密碼
  cid: "A123456789"
  # 測試使用者姓名
  name: "testA"
  # 測試使用者電話
  phone: "0983222111"
  # 測試使用者email
  email: "qwer1234@gmail.com"
  # 測試使用者身分證字號
  tw-person-id: "A223333333"
  # 測試使用者錢包密碼
  wallet-cid: "A123456789"
  # 測試使用者錢包密碼提示問題
  wallet-question: "你住哪裡?"
  # 測試使用者錢包密碼提示答案
  wallet-answer: "我住家裡"
  # 信箱驗證碼存活時間
  email-verify-code-survival-minute: 1440
  # 測試寄驗證信用信箱帳號
  test-send-email: "qwer1234@gmail.com"
  # 測試寄驗證信用信箱密碼
  test-email-cid: "qwer1234"
  # 發送驗證信間隔時間
  email-sending-cooldown-second: 30
