INSERT INTO mmdf.general_product (product_id, seller_id, category_id, name, description, price, quantity, review_status, product_status) VALUES (38, 1, 2, '破破爛爛三輪車', '最快時速10，帶你冒險世界！這輛車可能比您的阿嬤還老，但正因為如此，它才能給您帶來無與倫比的獨特體驗！我們的三輪車隨時隨地咣咣作響，彷彿在告訴您：‘我還在這裡，我還能走！’無論是鄉間小路還是城市街道，這三輪車都會帶給您驚喜和冒險。考慮一下我們的‘破爛三輪車’，絕對能給您一份笑料和冒險的滿滿收穫！', 30, 10, 0, 0);
INSERT INTO mmdf.general_product (product_id, seller_id, category_id, name, description, price, quantity, review_status, product_status) VALUES (39, 1, 3, '國王的新衣', '清透就像沒穿', 10, 50000, 2, 0);
INSERT INTO mmdf.general_product (product_id, seller_id, category_id, name, description, price, quantity, review_status, product_status) VALUES (40, 1, 4, '網紅的彩妝', '畫完像P圖一樣的顏料', 99, 200, 2, 0);
INSERT INTO mmdf.general_product (product_id, seller_id, category_id, name, description, price, quantity, review_status, product_status) VALUES (41, 1, 5, '遊X王卡', '遊X王卡全系列老闆跳樓賣', 1000000, 3, 0, 0);
INSERT INTO mmdf.general_product (product_id, seller_id, category_id, name, description, price, quantity, review_status, product_status) VALUES (42, 1, 6, '吳神滑鼠', '購買即可提升servlet技能，凡此滑鼠點擊處都會成功!', 888888888, 1, 0, 0);
INSERT INTO mmdf.general_product (product_id, seller_id, category_id, name, description, price, quantity, review_status, product_status) VALUES (43, 1, 5, 'Tibame空氣', '跟波卡空氣一樣是香的', 100, 1000000, 0, 0);
INSERT INTO mmdf.general_product (product_id, seller_id, category_id, name, description, price, quantity, review_status, product_status) VALUES (44, 1, 6, 'MMDF快樂購買', '我就是來置入式行銷!!!My My Dear Friends 與你同在~~~', 99999, 8888, 0, 0);
INSERT INTO mmdf.general_product (product_id, seller_id, category_id, name, description, price, quantity, review_status, product_status) VALUES (45, 1, 6, 'SQL營養液套組', '郭老師代言營養液讓你SQL指令通通聽話', 888888888, 1, 0, 0);
INSERT INTO mmdf.general_product (product_id, seller_id, category_id, name, description, price, quantity, review_status, product_status) VALUES (46, 1, 6, '面試順利包', '面試順利包，面試型男就該擁有這一款獨家包款!!賣到賺到', 888888888, 1, 1, 1);
INSERT INTO mmdf.general_product (product_id, seller_id, category_id, name, description, price, quantity, review_status, product_status) VALUES (47, 1, 1, '出清特賣!!B系列錶帶', '把你啊錶賣掉!!!( ง °д°)ง⁼³₌₃', 9999, 3, 2, 0);
INSERT INTO mmdf.general_product (product_id, seller_id, category_id, name, description, price, quantity, review_status, product_status) VALUES (48, 1, 1, '方向盤裝飾套-貓耳', '貓耳方向盤裝飾套提升方向感', 999, 10, 1, 1);
INSERT INTO mmdf.general_product (product_id, seller_id, category_id, name, description, price, quantity, review_status, product_status) VALUES (49, 1, 1, '行車充電器', '行車充電器喔~~~', 8, 100000, 0, 0);
INSERT INTO mmdf.general_product (product_id, seller_id, category_id, name, description, price, quantity, review_status, product_status) VALUES (50, 1, 1, 'BAW仿冒二手ㄅㄨ ㄅㄨ車', '買下BAW回味童年惡趣味', 1000000, 1, 1, 0);
INSERT INTO mmdf.general_product (product_id, seller_id, category_id, name, description, price, quantity, review_status, product_status) VALUES (51, 1, 1, '滿版Logo錶帶', '滿版單品，往往是視覺的第一焦點，經典永不過時', 8888, 2, 0, 0);
INSERT INTO mmdf.general_product (product_id, seller_id, category_id, name, description, price, quantity, review_status, product_status) VALUES (52, 1, 1, '錶帶-格紋棕', '編得好累，就是棕色格紋錶帶', 9999, 3, 1, 1);
INSERT INTO mmdf.general_product (product_id, seller_id, category_id, name, description, price, quantity, review_status, product_status) VALUES (53, 1, 1, '錶帶-格紋黑', '沒錯還是我，就是黑色格紋錶帶', 8888, 6, 0, 0);
INSERT INTO mmdf.general_product (product_id, seller_id, category_id, name, description, price, quantity, review_status, product_status) VALUES (54, 1, 1, '時空電話', '買下就可以跟時空中的自己對話，俗稱自言自語', 12, 99, 1, 1);
INSERT INTO mmdf.general_product (product_id, seller_id, category_id, name, description, price, quantity, review_status, product_status) VALUES (55, 1, 1, '就是錶', '饒了我，不想找圖，就是想好看，並且測試能不能開第二頁分頁而已', 145, 99, 1, 1);
INSERT INTO mmdf.general_product (product_id, seller_id, category_id, name, description, price, quantity, review_status, product_status) VALUES (56, 1, 2, '紅快木櫃', '紅快壞木櫃!!', 88, 99, 1, 1);
INSERT INTO mmdf.general_product (product_id, seller_id, category_id, name, description, price, quantity, review_status, product_status) VALUES (57, 1, 2, '木櫃-黑', '黑色木櫃', 999, 3, 0, 0);
INSERT INTO mmdf.general_product (product_id, seller_id, category_id, name, description, price, quantity, review_status, product_status) VALUES (58, 1, 2, '經典白木櫃', '經典喔~~~', 5555, 1, 1, 0);
INSERT INTO mmdf.general_product (product_id, seller_id, category_id, name, description, price, quantity, review_status, product_status) VALUES (59, 1, 2, '經典白木櫃二代', '經典喔~~~', 5555, 10, 0, 0);
INSERT INTO mmdf.general_product (product_id, seller_id, category_id, name, description, price, quantity, review_status, product_status) VALUES (60, 1, 2, '訂製書櫃', '訂製款書櫃', 58888, 3, 1, 1);
INSERT INTO mmdf.general_product (product_id, seller_id, category_id, name, description, price, quantity, review_status, product_status) VALUES (61, 1, 2, '米字腳木桌', '編得好累，就是米字腳木桌', 9999, 3, 1, 1);
INSERT INTO mmdf.general_product (product_id, seller_id, category_id, name, description, price, quantity, review_status, product_status) VALUES (62, 1, 2, '米字腳木桌-2', '編得好累，還是米字腳木桌', 9999, 8, 0, 0);
INSERT INTO mmdf.general_product (product_id, seller_id, category_id, name, description, price, quantity, review_status, product_status) VALUES (63, 1, 2, '不一樣的米字腳木桌', '不一樣的米字腳木桌!', 10000, 3, 1, 1);
INSERT INTO mmdf.general_product (product_id, seller_id, category_id, name, description, price, quantity, review_status, product_status) VALUES (64, 1, 2, '木桌', '木頭桌', 145, 3, 1, 1);
INSERT INTO mmdf.general_product (product_id, seller_id, category_id, name, description, price, quantity, review_status, product_status) VALUES (65, 1, 2, '木頭桌', '木頭桌', 1453, 1, 2, 0);
INSERT INTO mmdf.general_product (product_id, seller_id, category_id, name, description, price, quantity, review_status, product_status) VALUES (66, 1, 2, '珠寶燈', '藍寶石珠寶燈', 13212, 33, 0, 0);
INSERT INTO mmdf.general_product (product_id, seller_id, category_id, name, description, price, quantity, review_status, product_status) VALUES (67, 1, 2, '燈罩', '編織燈罩', 90000, 99, 2, 0);
INSERT INTO mmdf.general_product (product_id, seller_id, category_id, name, description, price, quantity, review_status, product_status) VALUES (68, 1, 3, '澎澎裙-童裝', '澎澎裙', 9999, 888, 1, 0);
INSERT INTO mmdf.general_product (product_id, seller_id, category_id, name, description, price, quantity, review_status, product_status) VALUES (69, 1, 3, '單寧外套', '單寧外套', 999, 3, 1, 1);
INSERT INTO mmdf.general_product (product_id, seller_id, category_id, name, description, price, quantity, review_status, product_status) VALUES (70, 1, 3, '包包', '包包', 888888, 2, 0, 0);
INSERT INTO mmdf.general_product (product_id, seller_id, category_id, name, description, price, quantity, review_status, product_status) VALUES (71, 1, 3, '包', '包', 9000000, 10, 1, 1);
INSERT INTO mmdf.general_product (product_id, seller_id, category_id, name, description, price, quantity, review_status, product_status) VALUES (72, 1, 3, '白包', '白包', 1000, 3, 0, 0);
INSERT INTO mmdf.general_product (product_id, seller_id, category_id, name, description, price, quantity, review_status, product_status) VALUES (73, 1, 3, 'ONE 寶寶上衣', 'ONE 寶寶上衣~', 8888, 3, 1, 1);
INSERT INTO mmdf.general_product (product_id, seller_id, category_id, name, description, price, quantity, review_status, product_status) VALUES (74, 1, 4, '層年洗澡水', '洗澡水', 9999, 9999, 0, 0);
INSERT INTO mmdf.general_product (product_id, seller_id, category_id, name, description, price, quantity, review_status, product_status) VALUES (75, 1, 4, '阿罵眼膜', '阿罵推薦的熊好用!', 999, 9999, 0, 0);
INSERT INTO mmdf.general_product (product_id, seller_id, category_id, name, description, price, quantity, review_status, product_status) VALUES (83, 1, 4, '髮夾', '髮夾 買一送十', 8, 999999, 0, 0);
INSERT INTO mmdf.general_product (product_id, seller_id, category_id, name, description, price, quantity, review_status, product_status) VALUES (84, 1, 5, '有Bug電腦', '有小惡魔的電腦', 1000000, 1, 0, 0);
INSERT INTO mmdf.general_product (product_id, seller_id, category_id, name, description, price, quantity, review_status, product_status) VALUES (85, 1, 4, '無良面霜', '無良事業要買要快', 12, 3, 1, 0);
INSERT INTO mmdf.general_product (product_id, seller_id, category_id, name, description, price, quantity, review_status, product_status) VALUES (86, 1, 2, '實木鷹椅', '傳鷹之寶', 120000, 3, 1, 0);
INSERT INTO mmdf.general_product (product_id, seller_id, category_id, name, description, price, quantity, review_status, product_status) VALUES (87, 1, 5, '菸盒', '懨懨菸菸盒', 1000, 99, 1, 0);
INSERT INTO mmdf.general_product (product_id, seller_id, category_id, name, description, price, quantity, review_status, product_status) VALUES (89, 1, 2, '收納架', '收納架附帶輪子', 321, 123, 1, 0);
INSERT INTO mmdf.general_product (product_id, seller_id, category_id, name, description, price, quantity, review_status, product_status) VALUES (90, 1, 6, '海鮮套餐', '大衛直營海鮮!!!你值得擁有!!!', 9000000, 1, 1, 0);
INSERT INTO mmdf.general_product (product_id, seller_id, category_id, name, description, price, quantity, review_status, product_status) VALUES (91, 1, 6, 'Java', 'JAVA~~', 9000000, 1, 1, 0);
INSERT INTO mmdf.general_product (product_id, seller_id, category_id, name, description, price, quantity, review_status, product_status) VALUES (92, 1, 6, '吳神滑鼠', '吳神滑鼠', 9000000, 99, 0, 1);
