spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/mmdf?serverTimezone=Asia/Taipei"
    username: "root"
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update
  # redis快取設定
  data:
    redis:
      host: "localhost"
      port: 6379
      password: "mmdf"

logging:
  file:
    path: "logs/"

config:
  # 是否使用local環境運行
  use-local: false
  #  跨域允許網域
  cors-allow-origin: "*"

